services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - "81:81"  # Mapea el puerto 80 del contenedor al puerto 80 de la máquina host
    environment:
      - ENVIRONMENT=production  # Puedes añadir tus variables de entorno aquí
    volumes:
      - .:/app  # Sincroniza el contenido del directorio actual con el directorio de trabajo en el contenedor
    restart: always  # Reinicia automáticamente el contenedor si se detiene
