name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' && github.base_ref == 'master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USER }}
          WORKDIR: /root/guimar_app
        run: |
          ssh $USERNAME@$HOST '
            cd $WORKDIR &&
            git pull origin master &&
            docker-compose down &&
            docker-compose up --build -d
          '
