name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Check Directory Contents
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USER }}
          WORKDIR: /root/guimar_app
        run: |
          ssh $USERNAME@$HOST "
            echo 'Contenido del directorio $WORKDIR:'
            ls -la $WORKDIR
          "

      - name: Deploy to VPS
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USER }}
          WORKDIR: /root/guimar_app
        run: |
          ssh $USERNAME@$HOST "
            cd $WORKDIR && \
            if [ ! -d '.git' ]; then
              echo 'Error: No es un repositorio Git. Verifica la ruta y el contenido.' && \
              exit 1
            fi && \
            git pull origin master && \
            docker-compose down && \
            docker-compose up --build -d
          "
